local set = vim.opt
set.shiftwidth = 4
set.number = true
set.relativenumber = true
set.wrap = false
set.guicursor = ""
set.nu = true
set.tabstop = 4
set.softtabstop = 4
set.expandtab = true
set.smartindent = true
set.wrap = false
set.swapfile = false
set.backup = false
set.undodir = os.getenv("HOME") .. "/.vim/undodir"
set.undofile = true
set.hlsearch = true
set.incsearch = true
set.termguicolors = true
set.scrolloff = 8
set.signcolumn = "yes"
set.isfname:append("@-@")
set.updatetime = 50
set.colorcolumn = "80"
set.cursorline = true
